# Generated by Django 3.1.2 on 2020-10-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201021_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-stats-up', 'Grafico'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design')], max_length=12, verbose_name='Icone'),
        ),
    ]
