# Generated by Django 3.1.2 on 2020-10-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201021_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('features', models.CharField(max_length=100, verbose_name='Features')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-package', 'Caixa'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-phone-handset', 'Telefone'), ('lni-map-marker', 'Marcador'), ('lni-laptop-phone', 'Laptop'), ('lni-leaf', 'Folha'), ('lni-star', 'Estrela'), ('lni-layers', 'Camadas'), ('lni-drop', 'Gota'), ('lni-stats-up', 'Grafico'), ('lni-rocket', 'Foguete'), ('lni-envelope', 'Envelope')], max_length=18, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Grafico'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
    ]
